version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2015

build:
  verbosity: minimal

after_build:
- cmd: >-
    "C:\Program Files (x86)\IIS Express\iisexpress.exe" /path:"src\WebSite" /port:58537
    "Tools\StaticSiteCrawler.cmd"