version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2015

build:
  verbosity: minimal

after_build:
- ps: >-
    $path = "$($buildFolder)\src\WebSite"
    $port = 58537

    $process = Start-Process 'C:\Program Files (x86)\IIS Express\iisexpress.exe' -NoNewWindow -ArgumentList "/path:$($path) /port:$($port)"